# Generated by Django 5.1.7 on 2025-04-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(choices=[('P', 'Pune'), ('M', 'Mumbai'), ('H', 'Hydrabad'), ('CSN', 'charapati Sambhaji Nager')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, choices=[('T', 'Technical'), ('NT', 'Non-Technical')], default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('skill_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Expert')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('sal', models.DecimalField(decimal_places=2, default='0', max_digits=15)),
                ('joining_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.dept')),
                ('skills', models.ManyToManyField(to='emp.skill')),
            ],
        ),
    ]
